// Copyright (c) dWallet Labs, Ltd.
// SPDX-License-Identifier: BSD-3-Clause-Clear

//! Ika System program Rust client.
//!
//! Generated by Codama from `idl/ika_system_program.json`.
//! Do not edit manually -- run `bun run generate-clients` to regenerate.

// pub mod generated;
